### ISSUE TITLE
Getting error attribute "rippleColor" is already defined

### ISSUE THREAD

**Issue by gouravd** [greenfrvr/rubber-loader#3]

**Comment by greenfrvr** [comment]
Thanks, I will rename this attribute it as soon as possible. 
By the way which additional libraries are you using?

**Comment by gouravd** [comment]
Actually there's quite a few :)

**Comment by newaddressunknown** [comment]
For me it looks like a problem with the appcompat support library:

> _/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.0/res/values/values.xml
> Error:(2) Attribute "rippleColor" has already been defined
> Error:Execution failed for task ':app:processDebugResources'.
>  com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     /opt/android-sdk/build-tools/23.0.0/aapt package -f --no-crunch -I /opt/android-sdk/platforms/android-23/android.jar -M */app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S */app/build/intermediates/res/debug -A 
> */app/build/intermediates/assets/debug -m -J /
> */app/build/generated/source/r/debug -F 
> */app/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package de.test._ -0 apk --output-text-symbols 
> */app/build/intermediates/symbols/debug
>   Error Code:
>     1
>   Output:
>     */app/build/intermediates/res/debug/values/values.xml:123: error: Attribute "rippleColor" has already been defined

**Comment by greenfrvr** [comment]
renamed attribute in version 1.1.1
